In [2]:
from Implementation import Resnet
import torch

In [6]:
img=torch.rand((1,3,224,224))

In [7]:
resnet50=Resnet(3,4,6,3)
resnet101=Resnet(3,4,23,3)
resnet152=Resnet(3,8,36,3)

In [9]:
resnet50(img)

torch.Size([1, 64, 112, 112]) conv1
torch.Size([1, 256, 56, 56]) conv2
torch.Size([1, 512, 28, 28]) conv3
torch.Size([1, 1024, 14, 14]) conv4
torch.Size([1, 2048, 7, 7]) conv5


tensor([[ 0.7576, -1.4381]], grad_fn=<AddmmBackward0>)

In [10]:
resnet101(img)

torch.Size([1, 64, 112, 112]) conv1
torch.Size([1, 256, 56, 56]) conv2
torch.Size([1, 512, 28, 28]) conv3
torch.Size([1, 1024, 14, 14]) conv4
torch.Size([1, 2048, 7, 7]) conv5


tensor([[ 0.0452, -0.1647]], grad_fn=<AddmmBackward0>)

In [11]:
resnet152(img)

torch.Size([1, 64, 112, 112]) conv1
torch.Size([1, 256, 56, 56]) conv2
torch.Size([1, 512, 28, 28]) conv3
torch.Size([1, 1024, 14, 14]) conv4
torch.Size([1, 2048, 7, 7]) conv5


tensor([[1.0185, 0.4404]], grad_fn=<AddmmBackward0>)